name: End-to-end tests
on: [deployment_status]

jobs:
  e2e:
    if: github.event.deployment_status.state == 'success'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: "master"

      - name: Install node
        uses: actions/setup-node@v2
        with:
          node-version: "18"
