name: End-to-end tests
on: [deployment_status]

jobs:
  e2e:
    if: github.event.deployment_status.state == 'success'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: 'master'

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install
        working-directory: ./e2e

      - name: Install Playwright
        run: npx playwright install
        working-directory: ./e2e

      - name: Run E2E tests
        run: npm run regression
        working-directory: ./e2e

      - name: Upload E2E Test Report Artifact
        uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report-e2e
          path: e2e/playwright-report/
          retention-days: 30
