name: Nightly run

on:
  schedule:
- cron: "50 13 * * *"  # Runs at 1:50 PM UTC, equivalent to 4:50 AM in Kyiv timezone (UTC+3) - for test

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install E2E dependencies
        run: npm install
        working-directory: ./e2e

      - name: Install Playwright browsers
        run: npx playwright install
        working-directory: ./e2e

      - name: Run smoke tests
        run: npm run smoke
        working-directory: ./e2e