name: Nightly run

on:
  schedule:
    - cron: "40 14 * * *" # Runs at 2:40 PM UTC, equivalent to 5:30 AM in Kyiv timezone (UTC+3) - for test


jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install E2E dependencies
        run: npm install
        working-directory: ./e2e

      - name: Install Playwright browsers
        run: npx playwright install
        working-directory: ./e2e

      - name: Run smoke tests
        run: npm run smoke
        working-directory: ./e2e

      - name: Upload Smoke Test Report Artifact
        uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-smoke-report-night-run
          path: e2e/playwright-report/
          retention-days: 30