name: PR to master

on:
  pull_request:
    branches: [ master ]

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22'
      - name: Install E2E dependencies
        run: npm install
        working-directory: ./e2e
      - name: Run Eslint
        run: npm run lint
        working-directory: ./e2e

  prettier:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22'
      - name: Install E2E dependencies
        run: npm install
        working-directory: ./e2e
      - name: Run Prettier
        run: npm run format
        working-directory: ./e2e

  ts_check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22'
      - name: Install E2E dependencies
        run: npm install
        working-directory: ./e2e
      - name: Run TypeScrip
        run: npm run tsc
        working-directory: ./e2e

  e2e_tests:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    needs: ts_check
    env:
      REPORT_PORTAL_ENDPOINT: ${{ secrets.REPORT_PORTAL_ENDPOINT }}
      REPORT_PORTAL_APIKEY: ${{ secrets.REPORT_PORTAL_APIKEY }}
      REPORT_PORTAL_PROJECT: ${{ secrets.REPORT_PORTAL_PROJECT }}
      REPORT_PORTAL_DESCRIPTION: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
      REPORT_PORTAL_LAUNCH_NAME: "PR Master Regression Tests"
    strategy:
      fail-fast: false
      matrix:
        shard: [1/4, 2/4,3/4,4/4]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22'
        
      - name: Install E2E dependencies
        run: npm install
        working-directory: ./e2e

      - name: Install Playwright browsers
        run: npx playwright install --with-deps
        working-directory: ./e2e

      - name: Run regression tests
        run: npm run regression --shard ${{ matrix.shard }}
        working-directory: ./e2e

      - name: Upload blob report to GitHub Actions Artifacts
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: blob-report
          path: blob-report
          retention-days: 1

  merge-reports:
    if: always()
    needs: [playwright-tests]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm install
        
      - name: Download blob reports from GitHub Actions Artifacts
       uses: actions/download-artifact@v3
       with:
          name: blob-report
          path: blob-report

      - name: Merge into HTML Report
        run: npx playwright merge-reports --reporter html ./blob-report
        
      - name: Upload HTML report
        uses: actions/upload-artifact@v3
        with:
          name: html-report--attempt-${{ github.run_attempt }}
          path: playwright-report
          retention-days: 14