name: PR to master

on:
  pull_request:
    branches: [master] 

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install E2E dependencies
        run: npm instal
        working-directory: ./e2e

      - name: Install Playwright browsers
        run: npx playwright install
        working-directory: ./e2e

      - name: Run regression tests
        run: npm run regression
        working-directory: ./e2e