name: PR to master

on:
  pull_request:
    branches: [master] 

jobs:
  tests:
    runs-on: ubuntu-latest
    env:
      LAUNCH_NAME: "PR Master Regression Tests"
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Display Environment Variables
        run: |
          echo "Launch Name: ${{ env.LAUNCH_NAME }}"
          echo "Report Portal Launch Name: ${{ env.REPORT_PORTAL_LAUNCH_NAME }}"

      - name: Install E2E dependencies
        run: npm install
        working-directory: ./e2e
      
      - name: Run Eslint
        run: npm run lint
        working-directory: ./e2e

      - name: Run Prettier
        run: npm run format
        working-directory: ./e2e

      - name: Install Playwright browsers
        run: npx playwright install --with-deps
        working-directory: ./e2e

      - name: Run regression tests
        run: npm run regression
        working-directory: ./e2e

      - name: Upload Test Report Artifact
        uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report-pr-master
          path: e2e/playwright-report/ 
          retention-days: 30
        env:
          REPORT_PORTAL_LAUNCH_NAME: ${{ env.LAUNCH_NAME }}