name: PR to master

on:
  pull_request:
    branches: [ master ]

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22'
      - name: Install E2E dependencies
        run: npm ci
        working-directory: ./e2e
      - name: Run Eslint
        run: npm run lint
        working-directory: ./e2e

  prettier:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22'
      - name: Install E2E dependencies
        run: npm ci
        working-directory: ./e2e
      - name: Run Prettier
        run: npm run format
        working-directory: ./e2e

  ts_check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22'
      - name: Install E2E dependencies
        run: npm ci
        working-directory: ./e2e
      - name: Run TypeScript
        run: npm run tsc
        working-directory: ./e2e

  e2e_tests:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    needs: ts_check
    env:
      CI: true
      REPORT_PORTAL_ENDPOINT: ${{ secrets.REPORT_PORTAL_ENDPOINT }}
      REPORT_PORTAL_APIKEY: ${{ secrets.REPORT_PORTAL_APIKEY }}
      REPORT_PORTAL_PROJECT: ${{ secrets.REPORT_PORTAL_PROJECT }}
      REPORT_PORTAL_DESCRIPTION: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
      REPORT_PORTAL_LAUNCH_NAME: "PR Master Regression Tests"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22'

      - name: Install E2E dependencies
        run: npm ci
        working-directory: ./e2e

      - name: Install Playwright browsers
        run: npx playwright install --with-deps
        working-directory: ./e2e

      - name: Run regression tests
        run: npm run regression -- --only-changed
        working-directory: ./e2e

      - name: Upload Test Report Artifact
        uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: e2e/playwright-report/
          retention-days: 30